### ISSUE TITLE
ArmorItem cast to ArmorItemSet - Server crash 3.0.0 Forge

### ISSUE THREAD

**Issue by Eterst** [chronosacaria/MCStoryModeArmors#2]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Failure Information

Crash with last version 3.0.0 of Forge. Downloaded from Curseforge

## Steps to Reproduce

Unknown

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Ubuntu 20.04 
* Mod version: 3.0.0
* Fabric/Forge: Forge

## Failure Logs

[crash-2022-09-13_01.33.19-server.txt](https://github.com/chronosacaria/MCStoryModeArmors/files/9553873/crash-2022-09-13_01.33.19-server.txt)

**Comment by chronosacaria** [comment]
Fixed in https://github.com/chronosacaria/MCStoryModeArmors/commit/7b8fdc0897ccfa31471c1443cba483aadc0c2170
